{{ docker.from("php-nginx") }}

{{ environment.mailbox() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ mailsandbox.ubuntu() }}

RUN set -x \
    {{ mailsandbox.roundcube() }}

{{ docker.expose('25 465 587 143 993') }}
