{{ docker.from("php", "alpine-php7") }}

{{ environment.web() }}
{{ environment.webPhp() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ nginx.alpine() }}

{{ docker.expose('80 443') }}
