{{ docker.from("php", "debian-8") }}

{{ environment.web() }}
{{ environment.webPhp() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ nginx.debian() }}

{{ docker.expose('80 443') }}
