{{ baselayout.dockerStage() }}

{{ docker.from("samson", user="zendesk") }}

{{ environment.general() }}
{{ environment.base() }}
{{ environment.baseApp() }}

###############################################################################
# Bootstrap
###############################################################################

{{ baselayout.copy() }}

RUN set -x \
    {{ bootstrap.debian('jessie') }}

###############################################################################
# Base
###############################################################################

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ ansible.debian() }}

RUN set -x \
    {{ base.debian() }}

###############################################################################
# Base-app
###############################################################################

RUN set -x \
    {{ baseapp.debian() }}

###############################################################################
# Samson
###############################################################################

RUN set -x \
    {{ samsonDeployment.general() }}

{{ docker.expose('80') }}
{{ docker.volume('/storage') }}

{{ docker.entrypoint("/entrypoint") }}
{{ docker.cmd("supervisord") }}
