{{ docker.from("php", "centos-7-php7") }}

{{ environment.web() }}
{{ environment.webPhp() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ apache.centos() }}

{{ docker.expose('80 443') }}
