{{ docker.from("bootstrap", "ubuntu-14.04") }}

{{ environment.base() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ base.ubuntu() }}

{{ docker.entrypoint("/entrypoint") }}
{{ docker.cmd("supervisord") }}
