{{ docker.from("php", "alpine-php5") }}

{{ environment.web() }}
{{ environment.webPhp() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ apache.alpine() }}

{{ docker.expose('80 443') }}
