{{ docker.from("php", "ubuntu-12.04") }}

{{ environment.web() }}
{{ environment.webPhp() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ nginx.ubuntu() }}

{{ docker.expose('80 443') }}
