{{ docker.from("bootstrap", "debian-7") }}

{{ environment.base() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ base.debian() }}

{{ docker.entrypoint("/entrypoint") }}
{{ docker.cmd("supervisord") }}
