{{ docker.from("php", "ubuntu-16.10") }}

{{ environment.web() }}
{{ environment.webPhp() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ apache.ubuntu16() }}

{{ docker.expose('80 443') }}
