{{ docker.from("php", "debian-7") }}

{{ environment.web() }}
{{ environment.webPhp() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ apache.debian7() }}

{{ docker.expose('80 443') }}
