{{ docker.from("bootstrap", "alpine") }}

{{ environment.base() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ base.alpine() }}

{{ docker.entrypoint("/entrypoint") }}
{{ docker.cmd("supervisord") }}
